apiVersion: v2
name: neon-proxy
description: Neon Proxy
type: application
version: 1.12.0
appVersion: "0.1.0"
kubeVersion: "^1.18.x-x"
home: https://neon.tech
sources:
  - https://github.com/neondatabase/neon
