apiVersion: v2
name: neon-minio
description: Neon MinIO
type: application
version: 1.0.0
appVersion: "0.1.0"
kubeVersion: "^1.18.x-x"
home: https://neon.tech
sources:
  - https://github.com/neondatabase/neon
