# Default values for neon-endpoint-storage.
image:
  repository: neondatabase/neon
  pullPolicy: Always
  tag: latest
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  annotations: {}
  type: ClusterIP
  port: 80

skipS3Check: true
settings:
  # If you use S3:
  #bucket_name: ""
  #bucket_region: ""
  #
  # If you use Azure:
  #container_name: ""
  #container_region: ""
  #storage_account: ""

  # public key as a Secret with pemfile.pem to validate JWT requests.
  # If /certs/dummy.pem, helm chart uses a dummy Secret for tests to pass,
  # otherwise secret will be mounted at this place and passed to config, so choose
  # any name
  pemfile: "/certs/dummy.pem"
  # port must match .Values.service.port
  listen: "0.0.0.0:80"

nodeSelector: {}
tolerations: []
affinity: {}

priorityClassName: ""

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: 10s
    scrapeTimeout: 10s
    selector: {}
